#SPDX-License-Identifier: MIT-0
---
# defaults file for deploy_landing

deploy_user: parloruser
landing_app_dir: /home/{{ deploy_user }}/landing
landing_image: ghcr.io/parlorhub/landing-page:latest
landing_port: 4321
