#SPDX-License-Identifier: MIT-0
---
# defaults file for redis

deploy_user: parloruser
redis_app_dir: /home/{{ deploy_user }}/redis
redis_data_dir: /home/{{ deploy_user }}/redis/data
redis_image: redis:7-alpine
redis_port: 6379
